# Generated by Django 4.2.2 on 2023-06-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaloperator',
            name='aadhar_back_photo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaloperator',
            name='aadhar_front_photo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaloperator',
            name='pan_photo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operator',
            name='aadhar_back_photo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operator',
            name='aadhar_front_photo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operator',
            name='pan_photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
