# Generated by Django 4.2.2 on 2023-06-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaloperator',
            name='aadhar_back_photo',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicaloperator',
            name='aadhar_front_photo',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicaloperator',
            name='monthly_subscription_fee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaloperator',
            name='pan_photo',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicaloperator',
            name='setup_fee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='aadhar_back_photo',
            field=models.FileField(blank=True, null=True, upload_to='operator/'),
        ),
        migrations.AddField(
            model_name='operator',
            name='aadhar_front_photo',
            field=models.FileField(blank=True, null=True, upload_to='operator/'),
        ),
        migrations.AddField(
            model_name='operator',
            name='monthly_subscription_fee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='pan_photo',
            field=models.FileField(blank=True, null=True, upload_to='operator/'),
        ),
        migrations.AddField(
            model_name='operator',
            name='setup_fee',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
