# Generated by Django 4.2.2 on 2023-06-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_historicaloperator_aadhar_back_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaloperator',
            name='aadhar_back_photo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicaloperator',
            name='aadhar_front_photo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicaloperator',
            name='pan_photo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='operator',
            name='aadhar_back_photo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='operator',
            name='aadhar_front_photo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='operator',
            name='pan_photo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
