# Generated by Django 4.2.2 on 2023-06-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_historicaloperator_aadhar_back_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busphotograph',
            name='bus',
        ),
        migrations.RemoveField(
            model_name='historicalbus',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalbus',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='historicalbusphotograph',
            name='bus',
        ),
        migrations.RemoveField(
            model_name='historicalbusphotograph',
            name='history_user',
        ),
        migrations.AddField(
            model_name='historicaloperator',
            name='email',
            field=models.EmailField(db_index=True, default='abc@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='operator',
            name='email',
            field=models.EmailField(default='abc@gmail.com', max_length=254, unique=True),
        ),
        migrations.DeleteModel(
            name='Bus',
        ),
        migrations.DeleteModel(
            name='BusPhotograph',
        ),
        migrations.DeleteModel(
            name='HistoricalBus',
        ),
        migrations.DeleteModel(
            name='HistoricalBusPhotograph',
        ),
    ]
