# Generated by Django 4.2.2 on 2023-06-21 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_busphotograph_bus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaloperator',
            name='email',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='email',
        ),
    ]
