# Generated by Django 4.2.2 on 2023-06-29 16:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceMatrix',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('price_matrix', models.JSONField(default=dict, null=True)),
                ('bus_route', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bus.busroute')),
            ],
        ),
    ]
