# Generated by Django 3.2.7 on 2023-07-06 17:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceMatrix',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('price_matrix', models.JSONField(blank=True, default=list)),
                ('bus_route', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bus.busroute')),
            ],
        ),
    ]
