"""
Django settings for account project.

Generated by 'django-admin startproject' using Django 4.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os
from pathlib import Path
from paytmpg import LibraryConstants

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$n_9n+%ofvlq7#nyhoj1e#bv%vyd8u(6ek4ff*@b=t!u)lz6uz'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
FIREBASE_KEY = "AAAAqG_Q9W8:APA91bGPBHtvDE7j3xEufnKP260v_AXwdjnofhB-SpxXhE8Jz-zgFpBiRtIE0odzv1fHgCAz2RsGbm0M52qF3KwTso3FwZ4m4gwxn9d0LTaBrpUkrqKgA2kKPpudeB5MeYJ1c1T6_vfy"
OP_FIREBASE_KEY = "AAAAd9kAAIA:APA91bFFN6gr5iLos938YLk1KkWscQn2DPnBkyP-kwaeIoB-YnsVR04rPT8qc5OrS3vcd3hZB6vEkbIvmoa51ZMHhhIps1D98BXFFy-UWBB9azNBUogzg1Wkm4RD16ZokxKCblaJdasD"
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'account',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'simple_history',
    # 'account',
    'bus',
    'route',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
]

CORS_ORIGIN_ALLOW_ALL = True

CORS_ALLOW_HEADERS = ['access-control-allow-headers', 'content-type', 'accept', 'accept-encoding', 'authorization',
                      'content-type', 'dnt', 'origin', 'user-agent', 'x-csrftoken', 'x-requested-with',
                      'access-control-allow-origin', 'accept']

CORS_ORIGIN_WHITELIST = (
    'http://localhost:8000',
    'http://localhost:5000',
    'http://localhost:3000',
)

ROOT_URLCONF = 'operator_bd.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'operator_bd.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'account.User'

# REST_FRAMEWORK = {
#     "EXCEPTION_HANDLER": "utils.exception_handler.custom_exception_handler",
#     "UNAUTHENTICATED_USER": None,
# }

# REST_FRAMEWORK = {
#     'DEFAULT_PERMISSION_CLASSES': (
#         'rest_framework.permissions.IsAuthenticated',
#     ),
#     'DEFAULT_AUTHENTICATION_CLASSES': (
#         'rest_framework.authentication.TokenAuthentication',
#     )
# }

# Environment
ENVIRONMENT = "local"
SERVER_URL = "http://127.0.0.1:8000"

# Slack token
SLACK_TOKEN = "xoxb-2597034669908-2884874866868-jXEORWuz6pit4AT97EpNwQ8R"

PAYTM_MID = "ApniBu44764651821302"
PAYTM_MKEY = "tpDLp2nDKb5tb5M%"

PAYTM_ENVIRONMENT = LibraryConstants.PRODUCTION_ENVIRONMENT
PAYTM_CALLBACK_URL = 'https://securegw.paytm.in/theia/paytmCallback?ORDER_ID==%s'
PAYTM_UPI_QRCODE_CREATE_URL = 'https://securegw.paytm.in/paymentservices/qr/create'
PAYTM_UPI_PAYMENT_STATUS_URL = 'https://securegw.paytm.in/v3/order/status'

# PhonePe Production Credentials
MERCHANTID = "APNIBUSONLINE"
SALT_KEY = "0845fb5d-c9e1-4bc4-82ec-dcfdcdaad028"
SALT_INDEX = "1"
ACCEPT_PAYMENT_URL = "https://mercury-t2.phonepe.com/v4/debit"
DEBIT_URL = "/v4/debit"
CHECK_STATUS_URL = "https://mercury-t2.phonepe.com/v3/transaction/{}/{}/status"

# Celery Setup
CELERY_BROKER_URL = 'redis://localhost:6379'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_CREATE_MISSING_QUEUES = True

# AWS Credentials
AWS_BUCKET_NAME = "apnibus-assets"
AWS_IMG_FOLDER = "push_notification_assets/imgs"
BUCKET_REGION_NAME = os.getenv("BUCKET_REGION_NAME", "ap-south-1")
#
# LOGGING = {
#     'version': 1,
#     'loggers': {
#         'apnibus': {
#             'handlers': ['debug', 'info', 'error', 'warning', 'critical'],
#             'level': 'DEBUG'
#         },
#     },
#     'handlers': {
#         'debug': {
#             'level': 'DEBUG',
#             'class': 'logging.FileHandler',
#             'formatter': 'simpleRe',
#             'filename': '/var/log/apnibus_logs/debug.log'
#         },
#         'info': {
#             'level': 'INFO',
#             'class': 'logging.FileHandler',
#             'formatter': 'simpleRe',
#             'filename': '/var/log/apnibus_logs/info.log'
#         },
#         'error': {
#             'level': 'ERROR',
#             'class': 'logging.FileHandler',
#             'formatter': 'simpleRe',
#             'filename': '/var/log/apnibus_logs/error.log'
#         },
#         'warning': {
#             'level': 'WARNING',
#             'class': 'logging.FileHandler',
#             'formatter': 'simpleRe',
#             'filename': '/var/log/apnibus_logs/warning.log'
#         },
#         'critical': {
#             'level': 'CRITICAL',
#             'class': 'logging.FileHandler',
#             'formatter': 'simpleRe',
#             'filename': '/var/log/apnibus_logs/critical.log'
#         },
#     },
#     'formatters': {
#         'simpleRe': {
#             'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
#             'style': '{',
#         },
#     }
# }
