# Generated by Django 4.2.2 on 2023-07-01 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalroutemissingtown',
            name='duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='routemissingtown',
            name='duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalroutemissingtown',
            name='missing_town',
            field=models.CharField(default='town', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='routemissingtown',
            name='missing_town',
            field=models.CharField(default='town', max_length=255, null=True),
        ),
    ]
