# Generated by Django 4.2.2 on 2023-07-01 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='busroutetown',
            name='missing_towns',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AddField(
            model_name='historicalbusroutetown',
            name='missing_towns',
            field=models.JSONField(default=list, null=True),
        ),
    ]
