# Generated by Django 4.2.2 on 2023-06-29 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busroute',
            name='via',
        ),
        migrations.RemoveField(
            model_name='historicalbusroute',
            name='via',
        ),
    ]
