# Generated by Django 4.2.2 on 2023-07-04 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0001_initial'),
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='townsearch',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='town_search_district', to='route.district'),
        ),
        migrations.AlterField(
            model_name='townsearch',
            name='town',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='town_search_towns', to='route.town'),
        ),
    ]
