# Generated by Django 3.2.7 on 2023-07-12 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busroutestowns',
            name='calculated_duration',
        ),
        migrations.RemoveField(
            model_name='busroutestowns',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='historicalbusroutestowns',
            name='calculated_duration',
        ),
        migrations.RemoveField(
            model_name='historicalbusroutestowns',
            name='duration',
        ),
    ]
