# Generated by Django 4.2.2 on 2023-06-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busroute',
            name='bus',
        ),
        migrations.RemoveField(
            model_name='busroute',
            name='route',
        ),
        migrations.RemoveField(
            model_name='historicalbusroute',
            name='bus',
        ),
        migrations.RemoveField(
            model_name='historicalbusroute',
            name='route',
        ),
        migrations.AddField(
            model_name='busroute',
            name='arrival_time',
            field=models.DateTimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='busroute',
            name='bus_number',
            field=models.CharField(default='APNI BUS', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='busroute',
            name='departure_time',
            field=models.DateTimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='busroute',
            name='from_town',
            field=models.CharField(default='from town', max_length=255),
        ),
        migrations.AddField(
            model_name='busroute',
            name='to_town',
            field=models.CharField(default='to town', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalbusroute',
            name='arrival_time',
            field=models.DateTimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='historicalbusroute',
            name='bus_number',
            field=models.CharField(db_index=True, default='APNI BUS', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalbusroute',
            name='departure_time',
            field=models.DateTimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='historicalbusroute',
            name='from_town',
            field=models.CharField(default='from town', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalbusroute',
            name='to_town',
            field=models.CharField(default='to town', max_length=255),
        ),
    ]
