# Generated by Django 4.2.2 on 2023-06-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='busroutetown',
            name='calculated_duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='busroutetown',
            name='day',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='busroutetown',
            name='duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='busroutetown',
            name='eta_status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('request_for_deletion', 'request_for_deletion'), ('deletion_ready', 'deletion_ready')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='busroutetown',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('request_for_deletion', 'request_for_deletion'), ('deletion_ready', 'deletion_ready')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalbusroutetown',
            name='calculated_duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='historicalbusroutetown',
            name='day',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='historicalbusroutetown',
            name='duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='historicalbusroutetown',
            name='eta_status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('request_for_deletion', 'request_for_deletion'), ('deletion_ready', 'deletion_ready')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalbusroutetown',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('request_for_deletion', 'request_for_deletion'), ('deletion_ready', 'deletion_ready')], default='active', max_length=20),
        ),
    ]
