# Generated by Django 4.2.2 on 2023-07-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_alter_townsearch_district_alter_townsearch_town'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltownsearch',
            name='district',
        ),
        migrations.RemoveField(
            model_name='historicaltownsearch',
            name='district_name',
        ),
        migrations.RemoveField(
            model_name='historicaltownsearch',
            name='town',
        ),
        migrations.RemoveField(
            model_name='historicaltownsearch',
            name='town_name',
        ),
        migrations.RemoveField(
            model_name='townsearch',
            name='district',
        ),
        migrations.RemoveField(
            model_name='townsearch',
            name='district_name',
        ),
        migrations.RemoveField(
            model_name='townsearch',
            name='town',
        ),
        migrations.RemoveField(
            model_name='townsearch',
            name='town_name',
        ),
        migrations.AddField(
            model_name='historicaltownsearch',
            name='towns',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='townsearch',
            name='towns',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
