# Generated by Django 4.2.2 on 2023-06-29 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_remove_busroute_via_remove_historicalbusroute_via'),
    ]

    operations = [
        migrations.RenameField(
            model_name='busroute',
            old_name='route_ids',
            new_name='route',
        ),
        migrations.RenameField(
            model_name='historicalbusroute',
            old_name='route_ids',
            new_name='route',
        ),
    ]
