# Generated by Django 3.2.7 on 2023-07-12 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_auto_20230712_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busroutestowns',
            name='eta_status',
        ),
        migrations.RemoveField(
            model_name='historicalbusroutestowns',
            name='eta_status',
        ),
    ]
