# Generated by Django 4.2.2 on 2023-06-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_remove_busroute_bus_remove_busroute_route_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busroute',
            name='arrival_time',
            field=models.DateTimeField(default='YYYY-MM-DD 00:00'),
        ),
        migrations.AlterField(
            model_name='busroute',
            name='departure_time',
            field=models.DateTimeField(default='YYYY-MM-DD 00:00'),
        ),
        migrations.AlterField(
            model_name='historicalbusroute',
            name='arrival_time',
            field=models.DateTimeField(default='YYYY-MM-DD 00:00'),
        ),
        migrations.AlterField(
            model_name='historicalbusroute',
            name='departure_time',
            field=models.DateTimeField(default='YYYY-MM-DD 00:00'),
        ),
    ]
