# Generated by Django 4.2.2 on 2023-06-22 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0004_alter_busroute_arrival_time_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalBusRoute',
        ),
    ]
