# Generated by Django 4.2.2 on 2023-06-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0005_delete_historicalbusroute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busroute',
            name='bus_number',
            field=models.CharField(default='APNI_BUS', max_length=255, unique=True),
        ),
    ]
