# Generated by Django 4.2.2 on 2023-06-22 11:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bus', '0006_alter_busroute_bus_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalBusRoute',
            fields=[
                ('created_on', models.DateTimeField(blank=True, db_column='created_on', editable=False)),
                ('updated_on', models.DateTimeField(blank=True, db_column='updated_on', editable=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid1, editable=False)),
                ('bus_number', models.CharField(db_index=True, default='APNI_BUS', max_length=255)),
                ('from_town', models.CharField(default='from town', max_length=255)),
                ('to_town', models.CharField(default='to town', max_length=255)),
                ('departure_time', models.DateTimeField(default=datetime.datetime(2022, 1, 1, 0, 0))),
                ('arrival_time', models.DateTimeField(default=datetime.datetime(2022, 1, 1, 0, 0))),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical bus route',
                'verbose_name_plural': 'historical bus routes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
