# Generated by Django 4.2.2 on 2023-06-22 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0001_initial'),
        ('bus', '0007_historicalbusroute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busroute',
            name='arrival_time',
        ),
        migrations.RemoveField(
            model_name='busroute',
            name='bus_number',
        ),
        migrations.RemoveField(
            model_name='busroute',
            name='departure_time',
        ),
        migrations.RemoveField(
            model_name='busroute',
            name='from_town',
        ),
        migrations.RemoveField(
            model_name='busroute',
            name='to_town',
        ),
        migrations.RemoveField(
            model_name='historicalbusroute',
            name='arrival_time',
        ),
        migrations.RemoveField(
            model_name='historicalbusroute',
            name='bus_number',
        ),
        migrations.RemoveField(
            model_name='historicalbusroute',
            name='departure_time',
        ),
        migrations.RemoveField(
            model_name='historicalbusroute',
            name='from_town',
        ),
        migrations.RemoveField(
            model_name='historicalbusroute',
            name='to_town',
        ),
        migrations.AddField(
            model_name='busroute',
            name='bus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bus.bus'),
        ),
        migrations.AddField(
            model_name='busroute',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='route.route'),
        ),
        migrations.AddField(
            model_name='historicalbusroute',
            name='bus',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bus.bus'),
        ),
        migrations.AddField(
            model_name='historicalbusroute',
            name='route',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='route.route'),
        ),
    ]
