# Generated by Django 4.2.2 on 2023-06-22 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0009_remove_busroute_bus_remove_busroute_route_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalBusRoute',
        ),
    ]
