# Generated by Django 4.2.2 on 2023-06-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0011_historicalbusroute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busroute',
            name='arrival_time',
            field=models.DateTimeField(default='2022-01-01T00:00:00'),
        ),
        migrations.AlterField(
            model_name='busroute',
            name='departure_time',
            field=models.DateTimeField(default='2022-01-01T00:00:00'),
        ),
        migrations.AlterField(
            model_name='historicalbusroute',
            name='arrival_time',
            field=models.DateTimeField(default='2022-01-01T00:00:00'),
        ),
        migrations.AlterField(
            model_name='historicalbusroute',
            name='departure_time',
            field=models.DateTimeField(default='2022-01-01T00:00:00'),
        ),
    ]
