# Generated by Django 4.2.2 on 2023-06-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0012_alter_busroute_arrival_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busroute',
            name='arrival_time',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='busroute',
            name='departure_time',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='historicalbusroute',
            name='arrival_time',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='historicalbusroute',
            name='departure_time',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
